name: 'GitHub Action for SiteTranslationsLint'
description: 'Ensure your PHP website localized strings are complete and never unused'
author: 'Spreaker Devs <support@spreaker.com>'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'shield'
  color: 'orange'
